const SUBSCRIPTION_UPDATE_PROCESS = 'SUBSCRIPTION_UPDATE_PROCESS';
const SUBSCRIPTION_UPDATE_SUCCESS = 'SUBSCRIPTION_UPDATE_SUCCESS';
const SUBSCRIPTION_UPDATE_FAILED = 'SUBSCRIPTION_UPDATE_FAILED';
const SUBSCRIPTION_UPDATE_COMPLETED = 'SUBSCRIPTION_UPDATE_COMPLETED';

const GET_SUBSCRIPTION_DATA_PROCESS = 'GET_SUBSCRIPTION_DATA_PROCESS';
const GET_SUBSCRIPTION_DATA_SUCCESS = 'GET_SUBSCRIPTION_DATA_SUCCESS';
const GET_SUBSCRIPTION_DATA_FAILED = 'GET_SUBSCRIPTION_DATA_FAILED';

export {
  SUBSCRIPTION_UPDATE_PROCESS,
  SUBSCRIPTION_UPDATE_SUCCESS,
  SUBSCRIPTION_UPDATE_FAILED,
  SUBSCRIPTION_UPDATE_COMPLETED,
  GET_SUBSCRIPTION_DATA_PROCESS,
  GET_SUBSCRIPTION_DATA_SUCCESS,
  GET_SUBSCRIPTION_DATA_FAILED,
};
