const ROOMS_REQUEST_PENDING = 'ROOMS_REQUEST_PENDING';
const ROOMS_REQUEST_SUCCESS = 'ROOMS_REQUEST_SUCCESS';
const ROOMS_REQUEST_FAILED = 'ROOMS_REQUEST_FAILED';
const UPDATE_BOOKED_HISTORY = 'UPDATE_BOOKED_HISTORY';
const LOAD_BOOKED_HISTORY = 'LOAD_BOOKED_HISTORY';
const LOAD_ROOMS = 'LOAD_ROOMS';
const CONFIRM_BOOKED_ROOM = 'CONFIRM_BOOKED_ROOM';

export {
  ROOMS_REQUEST_PENDING,
  ROOMS_REQUEST_SUCCESS,
  ROOMS_REQUEST_FAILED,
  UPDATE_BOOKED_HISTORY,
  LOAD_BOOKED_HISTORY,
  LOAD_ROOMS,
  CONFIRM_BOOKED_ROOM,
};
