const ROOMS_REQUEST_PENDING = 'ROOMS_REQUEST_PENDING';
const ROOMS_REQUEST_SUCCESS = 'ROOMS_REQUEST_SUCCESS';
const ROOMS_REQUEST_FAILED = 'ROOMS_REQUEST_FAILED';

const LOAD_ROOMS = 'LOAD_ROOMS';

export { ROOMS_REQUEST_PENDING, ROOMS_REQUEST_SUCCESS, ROOMS_REQUEST_FAILED, LOAD_ROOMS };
