const AUTH_PROCESS = 'AUTH_PROCESS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAILED = 'AUTH_FAILED';
const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export { AUTH_PROCESS, AUTH_SUCCESS, AUTH_FAILED, CLOSE_SNACKBAR };
