const AUTH_PROCESS = 'AUTH_PROCESS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAILED = 'AUTH_FAILED';
const BREAK_AUTH_PROCESS = 'BREAK_AUTH_PROCESS';

export { AUTH_PROCESS, AUTH_SUCCESS, AUTH_FAILED, BREAK_AUTH_PROCESS };
