const GET_ADDITIONAL_USER_DATA_PROCESS = 'GET_ADDITIONAL_USER_DATA_PROCESS';
const GET_ADDITIONAL_USER_DATA_SUCCESS = 'GET_ADDITIONAL_USER_DATA_SUCCESS';
const GET_ADDITIONAL_USER_DATA_FAILED = 'GET_ADDITIONAL_USER_DATA_FAILED';

export {
  GET_ADDITIONAL_USER_DATA_PROCESS,
  GET_ADDITIONAL_USER_DATA_SUCCESS,
  GET_ADDITIONAL_USER_DATA_FAILED,
};
