const USERNAME_UPDATE_PROCESS = 'USERNAME_UPDATE_PROCESS';
const USERNAME_UPDATE_SUCCESS = 'USERNAME_UPDATE_SUCCESS';
const USERNAME_UPDATE_FAILED = 'USERNAME_UPDATE_FAILED';
const USERNAME_UPDATE_COMPLETED = 'USERNAME_UPDATE_COMPLETED';

export {
  USERNAME_UPDATE_PROCESS,
  USERNAME_UPDATE_SUCCESS,
  USERNAME_UPDATE_FAILED,
  USERNAME_UPDATE_COMPLETED,
};
