const GET_ROOM_DETAILS_PROCESS = 'GET_ROOM_DETAILS_PROCESS';
const GET_ROOM_DETAILS_SUCCESS = 'GET_ROOM_DETAILS_SUCCESS';
const GET_ROOM_DETAILS_FAILED = 'GET_ROOM_DETAILS_FAILED';

export { GET_ROOM_DETAILS_PROCESS, GET_ROOM_DETAILS_SUCCESS, GET_ROOM_DETAILS_FAILED };
