const AUTH_PROCESS = 'AUTH_PROCESS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAILED = 'AUTH_FAILED';
const BREAK_AUTH_PROCESS = 'BREAK_AUTH_PROCESS';
const PRELOAD_AUTH_DATA = 'PRELOAD_AUTH_DATA';
const AUTH_REQUIRED = 'AUTH_REQUIRED';
const GOOGLE_AUTH_PROCESS = 'GOOGLE_AUTH_PROCESS';
const PASSWORD_RESET_PROCESS = 'PASSWORD_RESET_PROCESS';
const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';
const PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';

export {
  AUTH_PROCESS,
  AUTH_SUCCESS,
  AUTH_FAILED,
  BREAK_AUTH_PROCESS,
  PRELOAD_AUTH_DATA,
  AUTH_REQUIRED,
  GOOGLE_AUTH_PROCESS,
  PASSWORD_RESET_PROCESS,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_FAILED,
  PASSWORD_RESET_COMPLETED,
};
