const AUTH_PROCESS = 'AUTH_PROCESS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAILED = 'AUTH_FAILED';
const BREAK_AUTH_PROCESS = 'BREAK_AUTH_PROCESS';
const PRELOAD_AUTH_DATA = 'PRELOAD_AUTH_DATA';
const AUTH_REQUIRED = 'AUTH_REQUIRED';
const GOOGLE_AUTH_PROCESS = 'GOOGLE_AUTH_PROCESS';
const AUTH_LOGOUT_PROCESS = 'AUTH_LOGOUT_PROCESS';
const AUTH_LOGOUT_DONE = 'AUTH_LOGOUT_DONE';

export {
  AUTH_PROCESS,
  AUTH_SUCCESS,
  AUTH_FAILED,
  BREAK_AUTH_PROCESS,
  PRELOAD_AUTH_DATA,
  AUTH_REQUIRED,
  GOOGLE_AUTH_PROCESS,
  AUTH_LOGOUT_PROCESS,
  AUTH_LOGOUT_DONE,
};
