const AUTH_FAILED = 'AUTH_FAILED';
const AUTH_LOGOUT_DONE = 'AUTH_LOGOUT_DONE';
const AUTH_LOGOUT_PROCESS = 'AUTH_LOGOUT_PROCESS';
const AUTH_PROCESS = 'AUTH_PROCESS';
const AUTH_REQUIRED = 'AUTH_REQUIRED';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const BREAK_AUTH_PROCESS = 'BREAK_AUTH_PROCESS';
const GOOGLE_AUTH_PROCESS = 'GOOGLE_AUTH_PROCESS';
const PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';
const PASSWORD_RESET_PROCESS = 'PASSWORD_RESET_PROCESS';
const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
const PRELOAD_AUTH_DATA = 'PRELOAD_AUTH_DATA';

export {
  AUTH_FAILED,
  AUTH_LOGOUT_DONE,
  AUTH_LOGOUT_PROCESS,
  AUTH_PROCESS,
  AUTH_REQUIRED,
  AUTH_SUCCESS,
  BREAK_AUTH_PROCESS,
  GOOGLE_AUTH_PROCESS,
  PASSWORD_RESET_COMPLETED,
  PASSWORD_RESET_FAILED,
  PASSWORD_RESET_PROCESS,
  PASSWORD_RESET_SUCCESS,
  PRELOAD_AUTH_DATA,
};
