const EMAIL_UPDATE_PROCESS = 'EMAIL_UPDATE_PROCESS';
const EMAIL_UPDATE_SUCCESS = 'EMAIL_UPDATE_SUCCESS';
const EMAIL_UPDATE_FAILED = 'EMAIL_UPDATE_FAILED';

export { EMAIL_UPDATE_PROCESS, EMAIL_UPDATE_SUCCESS, EMAIL_UPDATE_FAILED };
