const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
const REGISTRATION_PROCESS = 'REGISTRATION_PROCESS';
const BREAK_REGISTRATION_PROCESS = 'BREAK_REGISTRATION_PROCESS';
const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export {
  REGISTRATION_REQUEST,
  REGISTRATION_PROCESS,
  BREAK_REGISTRATION_PROCESS,
  REGISTRATION_SUCCESS,
  REGISTRATION_FAILED,
};
