const UPDATE_ADDITIONAL_USER_DATA_PROCESS = 'UPDATE_ADDITIONAL_USER_DATA_PROCESS';
const UPDATE_ADDITIONAL_USER_DATA_SUCCESS = 'UPDATE_ADDITIONAL_USER_DATA_SUCCESS';
const UPDATE_ADDITIONAL_USER_DATA_FAILED = 'UPDATE_ADDITIONAL_USER_DATA_FAILED';
const UPDATE_ADDITIONAL_USER_DATA_COMPLETED = 'UPDATE_ADDITIONAL_USER_DATA_COMPLETED';

export {
  UPDATE_ADDITIONAL_USER_DATA_PROCESS,
  UPDATE_ADDITIONAL_USER_DATA_SUCCESS,
  UPDATE_ADDITIONAL_USER_DATA_FAILED,
  UPDATE_ADDITIONAL_USER_DATA_COMPLETED,
};
