const PASSWORD_UPDATE_PROCESS = 'PASSWORD_UPDATE_PROCESS';
const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
const PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED';
const PASSWORD_UPDATE_COMPLETED = 'PASSWORD_UPDATE_COMPLETED';

export {
  PASSWORD_UPDATE_PROCESS,
  PASSWORD_UPDATE_SUCCESS,
  PASSWORD_UPDATE_FAILED,
  PASSWORD_UPDATE_COMPLETED,
};
