const PASSWORD_RESET_PROCESS = 'PROCESS';
const PASSWORD_RESET_SUCCESS = 'SUCCESS';
const PASSWORD_RESET_FAILED = 'FAILED';
const PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';

export {
  PASSWORD_RESET_PROCESS,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_FAILED,
  PASSWORD_RESET_COMPLETED,
};
