const EMAIL_UPDATE_PROCESS = 'EMAIL_UPDATE_PROCESS';
const EMAIL_UPDATE_SUCCESS = 'EMAIL_UPDATE_SUCCESS';
const EMAIL_UPDATE_FAILED = 'EMAIL_UPDATE_FAILED';
const EMAIL_UPDATE_COMPLETED = 'EMAIL_UPDATE_COMPLETED';

const GET_ADDITIONAL_USER_DATA_PROCESS = 'GET_ADDITIONAL_USER_DATA_PROCESS';
const GET_ADDITIONAL_USER_DATA_SUCCESS = 'GET_ADDITIONAL_USER_DATA_SUCCESS';
const GET_ADDITIONAL_USER_DATA_FAILED = 'GET_ADDITIONAL_USER_DATA_FAILED';

const PASSWORD_UPDATE_PROCESS = 'PASSWORD_UPDATE_PROCESS';
const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
const PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED';
const PASSWORD_UPDATE_COMPLETED = 'PASSWORD_UPDATE_COMPLETED';

const UPDATE_ADDITIONAL_USER_DATA_PROCESS = 'UPDATE_ADDITIONAL_USER_DATA_PROCESS';
const UPDATE_ADDITIONAL_USER_DATA_SUCCESS = 'UPDATE_ADDITIONAL_USER_DATA_SUCCESS';
const UPDATE_ADDITIONAL_USER_DATA_FAILED = 'UPDATE_ADDITIONAL_USER_DATA_FAILED';
const UPDATE_ADDITIONAL_USER_DATA_COMPLETED = 'UPDATE_ADDITIONAL_USER_DATA_COMPLETED';

const USERNAME_UPDATE_PROCESS = 'USERNAME_UPDATE_PROCESS';
const USERNAME_UPDATE_SUCCESS = 'USERNAME_UPDATE_SUCCESS';
const USERNAME_UPDATE_FAILED = 'USERNAME_UPDATE_FAILED';
const USERNAME_UPDATE_COMPLETED = 'USERNAME_UPDATE_COMPLETED';

export {
  EMAIL_UPDATE_PROCESS,
  EMAIL_UPDATE_SUCCESS,
  EMAIL_UPDATE_FAILED,
  EMAIL_UPDATE_COMPLETED,
  GET_ADDITIONAL_USER_DATA_PROCESS,
  GET_ADDITIONAL_USER_DATA_SUCCESS,
  GET_ADDITIONAL_USER_DATA_FAILED,
  PASSWORD_UPDATE_PROCESS,
  PASSWORD_UPDATE_SUCCESS,
  PASSWORD_UPDATE_FAILED,
  PASSWORD_UPDATE_COMPLETED,
  UPDATE_ADDITIONAL_USER_DATA_PROCESS,
  UPDATE_ADDITIONAL_USER_DATA_SUCCESS,
  UPDATE_ADDITIONAL_USER_DATA_FAILED,
  UPDATE_ADDITIONAL_USER_DATA_COMPLETED,
  USERNAME_UPDATE_PROCESS,
  USERNAME_UPDATE_SUCCESS,
  USERNAME_UPDATE_FAILED,
  USERNAME_UPDATE_COMPLETED,
};
